format = """
$directory$ruby$lua$git_branch$line_break$time$character
"""
add_newline = true

[directory.substitutions]
'medaxion_site' = '~ pulse ~'
'central_information_service' = '~ cis ~'
'~/.config' = '~ dotfiles ~'

[git_branch]
ignore_branches = ['master', 'main']
style = '#737373'
format = '[$symbol$branch(:$remote_branch)]($style) '

[ruby]
symbol = ''
style = 'red'
format = '[$symbol($version)]($style) '

[time]
disabled = false
format = '[$time]($style) '
time_format = '%R'
style = '#737373'

[directory]
style = 'blue'

[character]
format = '[$symbol](%style) '
success_symbol = '[=>](bold #7fbfab)'
vimcmd_symbol = '[V](bold green) '
