theme = 'catppuccin_latte'

[editor]
line-number = 'relative'
true-color = true
mouse = false
cursorline = true
rulers = [80]

[editor.cursor-shape]
insert = 'bar'
select = 'underline'

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", ":w"]

# moving around window
C-h = 'jump_view_left' 
C-j = 'jump_view_down'
C-k = 'jump_view_up'
C-l = 'jump_view_right'
C-q = 'wclose'
t = ":sh echo %sh{echo a}"
